// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit() {
  return window['go']['controllers']['App']['Exit']();
}

export function GetAuthedUser() {
  return window['go']['controllers']['App']['GetAuthedUser']();
}

export function GetChatMessages(arg1) {
  return window['go']['controllers']['App']['GetChatMessages'](arg1);
}

export function GetChats() {
  return window['go']['controllers']['App']['GetChats']();
}

export function GetUser(arg1) {
  return window['go']['controllers']['App']['GetUser'](arg1);
}

export function GetUsers() {
  return window['go']['controllers']['App']['GetUsers']();
}

export function LogOut() {
  return window['go']['controllers']['App']['LogOut']();
}

export function Login(arg1, arg2) {
  return window['go']['controllers']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['controllers']['App']['Register'](arg1, arg2, arg3);
}

export function Search(arg1) {
  return window['go']['controllers']['App']['Search'](arg1);
}

export function SearchDht(arg1) {
  return window['go']['controllers']['App']['SearchDht'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['controllers']['App']['SendMessage'](arg1, arg2);
}

export function SendOffer(arg1) {
  return window['go']['controllers']['App']['SendOffer'](arg1);
}
