// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit() {
  return window['go']['controllers']['AuthController']['Exit']();
}

export function GetAuthedUser() {
  return window['go']['controllers']['AuthController']['GetAuthedUser']();
}

export function LogOut() {
  return window['go']['controllers']['AuthController']['LogOut']();
}

export function Login(arg1, arg2) {
  return window['go']['controllers']['AuthController']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['controllers']['AuthController']['Register'](arg1, arg2, arg3);
}

export function Search(arg1) {
  return window['go']['controllers']['AuthController']['Search'](arg1);
}

export function SetContext(arg1) {
  return window['go']['controllers']['AuthController']['SetContext'](arg1);
}
