// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Exit():Promise<void>;

export function GetAuthedUser():Promise<models.User>;

export function LogOut():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<any>;

export function Search(arg1:string):Promise<Array<string>>;

export function SetContext(arg1:context.Context):Promise<void>;
