// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMessagesByChatID(arg1) {
  return window['go']['controllers']['MessageController']['GetMessagesByChatID'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['controllers']['MessageController']['SendMessage'](arg1, arg2);
}
