// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetMessagesByChatID(arg1:string):Promise<Array<models.Message>>;

export function SendMessage(arg1:string,arg2:string):Promise<Array<models.Message>>;
