// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function SearchDht(arg1:string):Promise<models.User>;

export function SendOffer(arg1:string):Promise<void>;
