// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchDht(arg1) {
  return window['go']['controllers']['SignalingController']['SearchDht'](arg1);
}

export function SendOffer(arg1) {
  return window['go']['controllers']['SignalingController']['SendOffer'](arg1);
}
