// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetUser(arg1:string):Promise<models.User>;

export function GetUsers():Promise<Array<models.User>>;
