// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUser(arg1) {
  return window['go']['controllers']['UserController']['GetUser'](arg1);
}

export function GetUsers() {
  return window['go']['controllers']['UserController']['GetUsers']();
}
