// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
