// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}
