// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRooms():Promise<Array<main.user_model>>;

export function GetServers():Promise<Array<main.server_model>>;

export function GetUsers():Promise<Array<main.user_model>>;
