name: tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt update && sudo apt upgrade
        sudo apt install libgtk-3-dev libwebkit2gtk-4.1-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Run Wails build
      run: wails build

    - name: Test
      run: go test -v ./...
